---
galaxy_info:
  role_name: security
  author: mhdio64
  description: Security baseline for server-bootstrap.
  license: MIT
  min_ansible_version: "2.21.0"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - "9"
        - "10"

dependencies: []
