---
galaxy_info:
  role_name: common
  author: mhdio64
  description: OS baseline for server-bootstrap.
  license: MIT
  min_ansible_version: "2.21.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
