---
- name: Bootstrap | preflight
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Preflight | global checks
      ansible.builtin.import_tasks: tasks/preflight/global.yml

    - name: Preflight | common role checks
      ansible.builtin.import_role:
        name: common
        tasks_from: preflight
      when: bootstrap_common_enabled | default(true) | bool

    - name: Preflight | users role checks
      ansible.builtin.import_role:
        name: users
        tasks_from: preflight
      when: bootstrap_users_enabled | default(true) | bool

- name: Bootstrap | apply
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: common
      when: bootstrap_common_enabled | default(true) | bool
    - role: users
      when: bootstrap_users_enabled | default(true) | bool
