---
- name: Security | load platform-specific variables
  ansible.builtin.include_tasks: load_platform_vars.yml

- name: Security | configure unattended-upgrades backend
  ansible.builtin.include_tasks: backends/unattended_upgrades.yml
  when: security_backend == 'unattended_upgrades'

- name: Security | configure dnf-automatic backend
  ansible.builtin.include_tasks: backends/dnf_automatic.yml
  when: security_backend == 'dnf_automatic'
