---
galaxy_info:
  role_name: firewall
  author: mhdio64
  description: Host firewall policy for server-bootstrap.
  license: MIT
  min_ansible_version: "2.21.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
