---
galaxy_info:
  role_name: docker
  author: mhdio64
  description: Docker discovery and installation for server-bootstrap.
  license: MIT
  min_ansible_version: "2.21.0"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - trixie
    - name: EL
      versions:
        - "9"

dependencies: []
